### ISSUE TITLE
create sass version

### ISSUE THREAD

**Issue by dnomak** [flexiblegs/flexiblegs-scss-plus#10]

**Comment by mknadler** [comment]
I might start taking a crack at this tonight

**Comment by mknadler** [comment]
Am I correct in thinking that the idea for the Sass version is: maintain the same usage (adding classes to HTML), but provide settings and so forth?

**Comment by dnomak** [comment]
@mknadler examine code :)

``` scss
@mixin breakpoint($class) {

  @if $class == xs {
    @content;
  }

  @else if $class == sm {
    @media (min-width: 415px) { @content; }
  }

  @else if $class == md {
    @media (min-width: 668px) { @content; }
  }

  @else if $class == lg {
    @media (min-width: 769px) { @content; }
  }

  @else if $class == xl {
    @media (min-width: 1025px) { @content; }
  }

  @else {
    @warn "Breakpoint mixin supports: xs, sm, md, lg, xl";
  }

}

ul{
  @include wrap;

  @include breakpoint(xs) {
    $gutter: 2;
  }
  @include breakpoint(sm) {
    $gutter: 5;
  }
  @include breakpoint(md) {
    $gutter: 10;
  }
  @include breakpoint(lg) {
    $gutter: 15;
  }
  @include breakpoint(xl) {
    $gutter: 20;
  }
}

ul li {
  @include breakpoint(xs) {
    $row: 2;
    $col: 1;
  }
  @include breakpoint(sm) {
    $row: 3;
    $col: 1;
  }
  @include breakpoint(md) {
    $row: 12;
    $col: 6;
  }
  @include breakpoint(lg) {
    $row: 6;
    $col: 1;
  }
  @include breakpoint(xl) {
    $row: 5;
    $col: 1;
  }
}
```
